version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  web:
    image: leepslab/otree
    environment:
      - OTREE_PRODUCTION=0
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - DJANGO_LOG_LEVEL=DEBUG
    command: bash -c "otree resetdb --noinput && bash /code/runserver.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
  redisdata: